<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Tp1Commerce</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- Pilote PostgreSQL (dependance declaree, exigee par l'enonce) -->
    <PackageReference Include="Npgsql" Version="9.0.3" />
  </ItemGroup>

</Project>
